# Generated by Django 3.0.2 on 2020-01-25 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='LocationImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
